CampusAnnouncements/Models/Announcement.cs
using System;

namespace CampusAnnouncements.Models
{
    public class Announcement
    {
        public required string Title {get;set;}
        public required string Content {get;set;}
        public DateTime DatePost {get;set;}
    }
}

CampusAnnouncements/Models/ErrorViewModel.cs
namespace CampusAnnouncements.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

CampusAnnouncements/Controllers/AnnouncementsController.cs
using Microsoft.AspNetCore.Mvc;
using CampusAnnouncements.Models;
using CampusAnnouncements.Repositories;

namespace CampusAnnouncements.Controllers
{
    public class AnnouncementsController : Controller
    {
        private readonly AnnouncementRepository repository = new AnnouncementRepository();

        public ViewResult Index()
        {
            var announcements = repository.GetAllMyPost();
            return View(announcements);
        }

        [HttpGet]
        public ViewResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Announcement announcement)
        {
            repository.Add(announcement);
            return RedirectToAction("Index");
        }
    }
}

CampusAnnouncements/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using CampusAnnouncements.Models;

namespace CampusAnnouncements.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

CampusAnnouncements/Views/Announcements/Create.cshtml
@model CampusAnnouncements.Models.Announcement

@{
    ViewData["Title"] = "Create Annnouncements";
}

<h2>Add A New Announcement</h2>
<form method="post">
    <label>Title:</label>
    <input type="text" name="Title" class="form-control" required />
    
    <label>Content:</label>
    <textarea name="Content" class="form-control" required></textarea>
    
    <button type="submit" class="btn btn-primary mt-2">Submit</button>
</form>

CampusAnnouncements/Views/Announcements/Index.cshtml
@model List<CampusAnnouncements.Models.Announcement>

@{
    ViewData["Title"] = "Annnouncements";
}


<h2 class="display-4 my-5 text-center">Campus Announcements</h2>
<div class="row row-cols-1 w-100">
    @foreach (var announcement in Model)
    {
        <div class="col">
            <div class="card mb-3">
                <div class="card-header"><i class="bi bi-megaphone me-1"></i>Announcements Posted</div>
                <div class="card-body">
                    <h5 class="card-title text-info">@announcement.Title</h5>
                    <p class="card-text">@announcement.Content</p>
                    <p class="card-text text-end"><i class="bi bi-calendar-event me-1"></i><small class="text-muted">@announcement.DatePost.ToString("dddd, dd MMMM yyyy @ HH:mm:ss")</small></p>
                </div>
            </div>
        </div>

    }
</div>

CampusAnnouncements/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome To Our Campus</h1>
    <p>This is icetask 2 (I am going To try To deploy icetask with microsoft azure) </p>
</div>

CampusAnnouncements/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CampusAnnouncements.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-xl navbar-toggleable-sm border-bottom box-shadow mb-3 " style="background-color: #e3f2fd;">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Campus Announcements</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Announcements" asp-action="Index">Announcements</a>
                        </li>
                    </ul>
                    <div class="d-flex">
                        <a class="btn btn-outline-primary btn-sm" asp-controller="Announcements" asp-action="Create">Add Announcement</a>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Campus Announcements - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>